services:
    wordpress:
        image: wp_pokemon
        ports:
            - "80"
        labels:
            - traefik.enable=true
            - traefik.http.routers.pokeclub.rule=Host(`pokeclub.ju2breizh.fr`)
        build:
            context: .
        networks:
            - wpnet
            - webgateway

    db:
        image: mysql:latest
        ports:
            - "3306"
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - wpnet

volumes:
    db_data:

networks:
    wpnet:
    webgateway:
        external: true
